name: SimpleAuth
version: "1.0.0"
api: ["1.0.0"]
main: SimpleAuth.SimpleAuth
author: "CreeperFace"
description: "Auth plugin"

commands:
  login:
    description: "Select game kit"
    permission: "simpleauth.command.login"
  register:
    description: "join to blue team"
    permission: "simpleauth.command.register"
  changepassword:
    description: "join to red team"
    permission: "simpleauth.command.changepassword"
  unregister:
    description: "join to yellow team"
    permission: "simpleauth.command.unregister"

permissions:
  simpleauth:
    description: "Allows using everything SimpleAuth has"
    default: op
    children:
      simpleauth.move:
        description: "Allows moving while not being authenticated"
        default: false
      simpleauth.chat:
        description: "Allows using the chat while not being authenticated"
      simpleauth.command:
        description: "Allows using SimpleAuth commands"
        default: true
        children:
          simpleauth.command.register:
            description: "Allows registering an account"
            default: true
          simpleauth.command.login:
            description: "Allows logging into an account"
            default: true
          simpleauth.command.changepassword:
            description: "Allows change a password of an account"
            default: true
          simpleauth.command.unregister:
            description: "Allows unregistering an account"
            default: true